In [51]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split  
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
data=pd.read_csv('./Datasets/Data (1).csv')

In [5]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
data.shape

(10, 4)

In [39]:
x=data[['Country','Age','Salary']].values
y=data[['Purchased']].values
x[x == 'nan'] = np.nan

In [59]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [41]:
imputer=SimpleImputer(strategy='median')

In [42]:
imputer=imputer.fit(x[:,1:3])

In [45]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [46]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [48]:
LE=LabelEncoder()

In [49]:
x[:,0]=LE.fit_transform(x[:,0])

In [50]:
x


array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 61000.0],
       [0, 35.0, 58000.0],
       [2, 38.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [54]:
OHE=OneHotEncoder()

In [56]:
OHE.fit_transform(x[:,0].reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [57]:
y=LE.fit_transform(y)

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [60]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])