In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4,5],[
    6,7,8,9,10]])

In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
arr.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [5]:
arr.sum(axis=1)

array([15, 40])

In [6]:
arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [7]:
arr.ndim

2

In [8]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [9]:
arr.size

10

In [10]:
arr.nbytes

80

In [11]:
one=np.array([1,7,2,3,9])

In [12]:

one.argsort()

array([0, 2, 3, 1, 4])

In [13]:
one.argmax()


np.int64(4)

In [14]:

one.argmin()

np.int64(0)

In [15]:
two=np.array([[3,8,2,4,0,1],
              [1,6,2,0,8,3]])

In [16]:
two

array([[3, 8, 2, 4, 0, 1],
       [1, 6, 2, 0, 8, 3]])

In [17]:
two.argmax(axis=0)

array([0, 0, 0, 0, 1, 1])

In [18]:
two.argmax(axis=1)

array([1, 4])

In [19]:
two.argmin(axis=0)

array([1, 1, 0, 1, 0, 0])

In [20]:
two.argmin(axis=1)

array([4, 3])

In [21]:
two.argsort(axis=0)

array([[1, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1]])

In [22]:
two.argsort(axis=1)

array([[4, 5, 2, 0, 3, 1],
       [3, 0, 2, 5, 1, 4]])

In [23]:
two.ravel() 

array([3, 8, 2, 4, 0, 1, 1, 6, 2, 0, 8, 3])

In [24]:
two.reshape((4,3))

array([[3, 8, 2],
       [4, 0, 1],
       [1, 6, 2],
       [0, 8, 3]])

In [25]:
two.reshape((12,1))

array([[3],
       [8],
       [2],
       [4],
       [0],
       [1],
       [1],
       [6],
       [2],
       [0],
       [8],
       [3]])

In [26]:
two.reshape((1,12))

array([[3, 8, 2, 4, 0, 1, 1, 6, 2, 0, 8, 3]])

In [27]:
two

array([[3, 8, 2, 4, 0, 1],
       [1, 6, 2, 0, 8, 3]])