In [1]:
import numpy as np

In [2]:
ar1=np.array([[6,1,9],[1,8,2],[5,0,2]])

In [3]:
ar2=np.array([[2,0,4],[8,2,6],[4,3,9]])

In [4]:
ar1+ar2

array([[ 8,  1, 13],
       [ 9, 10,  8],
       [ 9,  3, 11]])

In [5]:
ar1*ar2

array([[12,  0, 36],
       [ 8, 16, 12],
       [20,  0, 18]])

In [6]:
ar1-ar2

array([[ 4,  1,  5],
       [-7,  6, -4],
       [ 1, -3, -7]])

In [7]:
ar1/ar2

/tmp/ipykernel_10078/54374712.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/ar2


array([[3.        ,        inf, 2.25      ],
       [0.125     , 4.        , 0.33333333],
       [1.25      , 0.        , 0.22222222]])

In [8]:
ar1%ar2

/tmp/ipykernel_10078/107717858.py:1: RuntimeWarning: divide by zero encountered in remainder
  ar1%ar2


array([[0, 0, 1],
       [1, 0, 2],
       [1, 0, 2]])

In [9]:
ar1//ar2

/tmp/ipykernel_10078/2793834162.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  ar1//ar2


array([[3, 0, 2],
       [0, 4, 0],
       [1, 0, 0]])

In [10]:
[5,8,1]+[6,7,3]

[5, 8, 1, 6, 7, 3]

In [11]:
np.sqrt(ar1)

array([[2.44948974, 1.        , 3.        ],
       [1.        , 2.82842712, 1.41421356],
       [2.23606798, 0.        , 1.41421356]])

In [12]:
ar1

array([[6, 1, 9],
       [1, 8, 2],
       [5, 0, 2]])

In [13]:
np.sqrt(ar1)

array([[2.44948974, 1.        , 3.        ],
       [1.        , 2.82842712, 1.41421356],
       [2.23606798, 0.        , 1.41421356]])

In [14]:
ar1.sum()

np.int64(34)

In [15]:
ar1.min()

np.int64(0)

In [16]:
ar1.max()

np.int64(9)

In [17]:
np.where(ar1>5)

(array([0, 0, 1]), array([0, 2, 1]))

In [18]:
type(np.where(ar1>5))

tuple

In [19]:
np.count_nonzero(ar1)

8

In [20]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 2]))

In [21]:
type(np.nonzero(ar1))

tuple

In [22]:
ar1[0,0]=0

In [23]:
np.nonzero(ar1)

(array([0, 0, 1, 1, 1, 2, 2]), array([1, 2, 0, 1, 2, 0, 2]))